config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :jobs do
    collection do
      get :search
    end

    resources :resumes
  end

  root 'welcome#index'


	namespace :admin do
    resources :jobs do
      member do
        get :publish
        post :hide
      end
      resources :resumes
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/job.rb
# == Schema Information
#
# Table name: jobs
#
#  id               :integer          not null, primary key
#  title            :string
#  description      :text
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  wage_upper_bound :integer
#  wage_lower_bound :integer
#  contact_email    :string
#  is_hidden        :boolean          default("t")
#

class Job < ApplicationRecord
	validates :title, presence: true
	validates :wage_upper_bound, presence: true
  	validates :wage_lower_bound, presence: true
  	validates :wage_lower_bound, numericality: { greater_than: 0}

  	scope :recent, -> {order("created_at DESC")}
    scope :published, -> { where(is_hidden: false) }

    has_many :resumes

  	def publish!
  		self.is_hidden = false
  		self.save
  	end

  	def hide!
  		self.is_hidden = true
  		self.save
  		
  	end

end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  title      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Post < ApplicationRecord
end

app/models/resume.rb
# == Schema Information
#
# Table name: resumes
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  job_id     :integer
#  content    :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  attachment :string
#

class Resume < ApplicationRecord
	belongs_to :user
	belongs_to :job

	mount_uploader :attachment, AttachmentUploader
	validates :content, presence: true
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default("0"), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  is_admin               :boolean          default("f")
#

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         has_many :resumes

         def admin?
         	is_admin
         	
         end
end

app/controllers/admin/jobs_controller.rb
class Admin::JobsController < ApplicationController
	before_action :authenticate_user!,only:[:new,:create,:update,:edit,:destroy]
	before_action :set_admin_job,only:[:show,:edit,:update,:destroy,:publish,:hide]
	before_action :require_is_admin
	layout "admin"

	def index
		# @jobs =Job.all.recent
		@jobs = case params[:order]
            when 'by_lower_bound'
              Job.published.order('wage_lower_bound DESC')
            when 'by_upper_bound'
              Job.published.order('wage_upper_bound DESC')
            else
              Job.published.recent
            end
		
	end

	def new
		@job =Job.new
		
	end

	def show
		
	end

	def edit
		
	end

	def destroy
		@job.destroy
		redirect_to admin_jobs_path
		
	end

	def create
		@job=Job.new(job_params)
		if @job.save
			redirect_to admin_jobs_path
		else
			render :new
			
		end
	end

	def update
		if @job.update(job_params)
			redirect_to admin_jobs_path
		else
			render :edit
		end
		
	end

	def publish
		@job.publish!
		redirect_to :back
		
	end

	def hide
		@job.hide!
		redirect_to :back
		
	end

	private

	def set_admin_job
		@job =Job.find(params[:id])
		
	end

	def job_params
		params.require(:job).permit(:title,:description,:wage_upper_bound,:wage_lower_bound,:contact_email,:contact_address,:contact_phone,:is_hidden)
	end
end

app/controllers/admin/resumes_controller.rb
class Admin::ResumesController < ApplicationController
	 before_action :authenticate_user!
  before_action :require_is_admin

  layout 'admin'

  def index
    @job = Job.find(params[:job_id])
    @resumes = @job.resumes.order('created_at DESC')
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def require_is_admin
  	if !current_user.admin?
  		flash[:alert] = 'You are not admin'
  		redirect_to root_path
  	end
  end

end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :validate_search_key, only: [:search]

	def index
		# @jobs  =Job.where(:is_hidden => false).recent
		  @jobs = case params[:order]
            when 'by_lower_bound'
              Job.published.order('wage_lower_bound DESC')
            when 'by_upper_bound'
              Job.published.order('wage_upper_bound DESC')
            else
              Job.published.recent
            end
		
	end

	def new
		@job =Job.new
	end
	
  def show
  @job = Job.find(params[:id])
  
    if@job.is_hidden
    flash[:warning]= "出错了"
    redirect_to root_path
    end
    
  end

  def search
    if @query_string.present?
    search_result = Job.published.ransack(@search_criteria).result(:distinct => true)
    @jobs = search_result.recent.paginate(:page => params[:page], :per_page => 5 )
    end
  end

protected

  def validate_search_key
    @query_string = params[:q].gsub(/\\|\'|\/|\?/, "")
    if params[:q].present?
      @search_criteria =  {
        title_cont: @query_string
      }
    end
  end

  def search_criteria(query_string)
    { :title_cont => query_string }
  end

def job_params
    params.require(:job).permit(:title,:description,:wage_upper_bound,:wage_lower_bound,:contact_email,:contact_address,:contact_phone,:is_hidden)
  end

end

app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
	before_action :authenticate_user!

  def new
    @job = Job.find(params[:job_id])
    @resume = Resume.new
  end

  def create
    @job = Job.find(params[:job_id])
    @resume = Resume.new(resume_params)
    @resume.job = @job
    @resume.user = current_user

    if @resume.save
      flash[:notice] = "成功提交履历"
      redirect_to job_path(@job)
    else
      render :new
    end
  end

  private

  def resume_params
    params.require(:resume).permit(:content,:attachment)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
    
  end

end

app/helpers/admin/jobs_helper.rb
module Admin::JobsHelper
end

app/helpers/admin/resumes_helper.rb
module Admin::ResumesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
def resource_name
    :user
  end

  def resource
      @resource ||= User.new
  end

  def resource_class
      User
  end

  def devise_mapping
      @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/flashes_helper.rb
module FlashesHelper
  FLASH_CLASSES = { alert: "danger", notice: "success", warning: "warning"}.freeze

  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end

  def user_facing_flashes
    flash.to_hash.slice "alert", "notice","warning" 
  end
end

app/helpers/jobs_helper.rb
module JobsHelper
	def render_job_status(job)
		if job.is_hidden
      content_tag(:span, "", :class => "fa fa-lock")
    else
      content_tag(:span, "", :class => "fa fa-globe")
    end

		
	end

	def render_highlight_content(job,query_string)
    excerpt_cont = excerpt(job.title, query_string, radius: 500)
    highlight(excerpt_cont, query_string)
  end
  
end

app/helpers/resume_helper.rb
module ResumeHelper
end

app/helpers/resumes_helper.rb
module ResumesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/jobs/_form.html.erb
<%= simple_form_for [:admin, @job ] do |f| %>

<%= f.input :title ,label:'职位名称',error:'职位名称不得为空'%>
<%= f.input :description ,label:'岗位要求',error:'岗位要求不得为空'%>
<%= f.input :wage_lower_bound,label:'最低工资',error:'最低工资不得为空'%>
<%= f.input :wage_upper_bound,label:'最高工资',error:'最高工资不得为空'%>
<%= f.input :contact_email,label:'电子邮件',error:'电子邮件不得为空',placehoder:'user@qq.com'%>
<%= f.input :contact_phone,label:'联系电话',error:'联系电话不得为空'%>
<%= f.input :contact_address,label:'地址',error:'地址不得为空'%>
<%= f.input :is_hidden %>

  <%= f.submit "发布" ,class:'btn btn-primary'%>
<% end %>

app/views/admin/jobs/edit.html.erb
<h1> 编辑工作岗位</h1>


<%= render "form"%>

app/views/admin/jobs/index.html.erb
<div class="pull-right">
  <%= link_to("发布工作", new_admin_job_path, :class => "btn btn-default" ) %>
</div>

<div class="dropdown clearfix pull-right">
     <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenuDivider" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
       排序
         <span class="caret"></span>
     </button>
     <ul class="dropdown-menu" aria-labelledby="dropdownMenuDivider">
         <li>
           <%= link_to("按工资下限排序", admin_jobs_path(:order => "by_lower_bound")) %>
         </li>
         <li>
             <%= link_to("按工资上限排序", admin_jobs_path(:order => "by_upper_bound")) %>
 
         </li>
         <li>
           <%= link_to("发布时间", admin_jobs_path ) %>
 
         </li>
     </ul>
 </div>

<table class="table table-boldered table-striped custab">
<thead>
  <tr>
  <td>职位</td>
  <td>收到简历数</td>
  <td>工资范围</td>
 
  <td>管理选项</td>
  <td>发布时间</td>
</tr>
</thead>
<tbody>

  <% @jobs.each do |job| %>
  <tr>
    <td>
    <%= render_job_status(job) %>
      <%= link_to(job.title, admin_job_path(job)) %>
    </td>
    <td>
      <%= link_to(job.resumes.count, admin_job_resumes_path(job)) %>
    </td>
    <td >
      <span class="badge">¥ <%= job.wage_lower_bound%> - <%= job.wage_upper_bound%></span>
      
    </td>
   
    <td>
      <%= link_to edit_admin_job_path(job), :class => "btn btn-xs btn-info" do%> <i class="fa fa-pencil"></i> <%end%>
      <%= link_to admin_job_path(job), :method => :delete, :data => { :confirm => "Are you sure?" } ,:class => "btn btn-xs btn-danger" do %><i class="fa fa-trash"></i> <%end%>
         <% if job.is_hidden %>

      <%= link_to publish_admin_job_path(job), :class => "btn btn-xs btn-success" do%><i class="fa fa-eye"></i> <% end %>
    <% else %>
      <%= link_to hide_admin_job_path(job), :method => :post,  :class => "btn btn-xs btn-warning" do %><i class="fa fa-eye-slash"></i><% end %>
    <% end %>


    </td>
    <td>
      <%= job.created_at.to_date %>
    </td>
  </tr>
  <% end %>
</tbody>
</table>

app/views/admin/jobs/new.html.erb
<h1> 发布工作岗位</h1>

<%= render "form" %>

app/views/admin/jobs/show.html.erb
<h1> <%= @job.title %> </h1>

<p>
  <%= simple_format(@job.description) %>

</p>

app/views/admin/resumes/_resume.html.erb
<div class="panel panel-default">
    <div class="panel-heading">
        <div class="row">
            <div class="col-md-12">
                <h3 class="panel-title">
                    <%= resume.user.email %>
                </h3>
            </div>

        </div>
    </div>
    <div class="panel-body">
        <div class="trix-content">
            <p> <%= simple_format(resume.content) %> </p>
        </div>

        <hr>

        <% if resume.attachment.present? %>
          <i class="fa fa-paperclip"> </i>
          <%= link_to("Download Resume", resume.attachment_url) %>
        <% else %>
           No Attachment
        <% end %>
    </div>

</div>

app/views/admin/resumes/index.html.erb
<h2> <%= @job.title %> - 履历列表 </h2>

<hr>
<%= render :partial => "resume", :collection => @resumes, :as => :resume %>

app/views/common/_flashes.html.erb
<% if flash.any? %>
  <% user_facing_flashes.each do |key, value| %>
    <div class="alert alert-dismissable alert-<%= flash_class(key) %>">
      <button class="close" data-dismiss="alert">×</button>
      <%= value %>
    </div>
  <% end %>
<% end %>

app/views/common/_footer.html.erb
<footer class="text-center ">
  <div class="footer-below">
      <p class="text-center">Copyright ©2017 仙居本地
          <br>Design by kmind
      </p>
  </div>
</footer>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default " role="navigation">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <a class="navbar-brand" href="/"><img src="<%= image_url 'user.png'%>">仙居本地招聘网</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

            <ul class="nav navbar-nav">
              <li>
                <div class="form-group form-inline search-bar">
                  <%= render :partial => "jobs/search_bar"%>
                </div>
              </li>
            </ul>

            <!-- <form class="navbar-form navbar-left" role="search">
                <div class="form-group">
                <input type="text" class="form-control" placeholder="Search">
                </div>
                <button type="submit" class="btn btn-default">Submit</button>
            </form> -->

            <ul class="nav navbar-nav navbar-right">
                 <% if !current_user %>
                  <li><a href="#" data-toggle="modal" data-target="#signup-modal">注册</a></li>
<li><a href="#" data-toggle="modal" data-target="#login-modal">登入</a></li>

                <% else %>
                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        Hi!, <%= current_user.email %>
                        <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                    <% if current_user.admin? %>
                    <li> <%= link_to("管理员后台", admin_jobs_path) %> </li>
                    <% end %>
                        <li> <%= link_to("退出", destroy_user_session_path, method: :delete) %> </li>
                    </ul>
                  </li>
                <% end %>

            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>

<div class="modal fade" id="login-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
  <div class="modal-dialog" role="document">
    <div class="loginmodal-container">
       <h2>Log in</h2>
       <%= simple_form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
         <div class="form-inputs">
           <%= f.input :email, required: false, autofocus: true %>
           <%= f.input :password, required: false %>
           <%= f.input :remember_me, as: :boolean if devise_mapping.rememberable? %>
         </div>
         <div class="form-actions">
           <%= f.button :submit, "Log in" %>
         </div>
       <% end %>
    </div>
  </div>
</div>

<div class="modal fade" id="signup-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
  <div class="modal-dialog">
    <div class="loginmodal-container">
      <h2>Sign up</h2>
        <%= simple_form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
        <%= f.error_notification %>
        <div class="form-inputs">
          <%= f.input :email, required: true, autofocus: true %>
          <%= f.input :password, required: true, hint: ("#{@minimum_password_length} characters minimum" if @minimum_password_length) %>
          <%= f.input :password_confirmation, required: true %>
        </div>
        <div class="form-actions">
            <%= f.button :submit, "Sign up" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/jobs/_search_bar.html.erb
<div class="row">
  <div class="col-sm-9 col-lg-8 col-lg-offset-2">
   

    <div class="nav navbar-nav navbar-left">
       <%= form_tag search_jobs_path , :method => :get do %>
      <div class="input-group" id="search-id" >
        <input type="text" class="form-control" name="q" value="<%= params[:q] %>" placeholder="请输入职位信息">
        <div class="input-group-btn">
          <button class="btn btn-default" type="submit">
            <i class="glyphicon glyphicon-search"></i>
          </button>
        </div>

      </div>
      <% end %>
    </div>
    
  </div>
</div>

app/views/jobs/index.html.erb
<div class="dropdown clearfix pull-right">
     <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenuDivider" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
       排序
         <span class="caret"></span>
     </button>
     <ul class="dropdown-menu" aria-labelledby="dropdownMenuDivider">
         <li>
           <%= link_to("按工资下限排序", jobs_path(:order => "by_lower_bound")) %>
         </li>
         <li>
             <%= link_to("按工资上限排序", jobs_path(:order => "by_upper_bound")) %>
 
         </li>
         <li>
           <%= link_to("发布时间", jobs_path ) %>
 
         </li>
     </ul>
 </div>

<table class="table table-boldered table-striped custab">
<thead>
  <tr>
  <td>职位</td>
  <td>竞争人数</td>
  <td>工资范围</td>
 <td>发布时间</td>
  <td>操作</td>
  
</tr>
</thead>
<tbody>

  <% @jobs.each do |job| %>
  <tr>
    <td>
    <%= render_job_status(job) %>
      <%= link_to(job.title, job_path(job)) %>
    </td>
    <td>
      <%= job.resumes.count %>
    </td>
    <td >
      <span class="badge">¥ <%= job.wage_lower_bound%> - <%= job.wage_upper_bound%></span>
      
    </td>
   
   <td>
      <%= job.created_at.to_date %>
    </td>

    <td>
      
                        <%= link_to("应征", new_job_resume_path(job), class: "btn btn-xs btn-success", method: :get) %>
                      


    </td>
    
  </tr>
  <% end %>
</tbody>
</table>

app/views/jobs/search.html.erb
<div>
  <br>
<% if @query_string.blank? %>
    <div class="search-info-title">
      Sorry, The search content cannot be blank, please type some product into to search.
    </div>
    
  <% elsif @jobs.blank? %>
    <br>
    <h2 class="search-info-title">搜索信息不能为空，请输入关键字搜索</h2>
  <% else %>
    <h2 class="search-info-title"> 有关"<%= @query_string %>"的工作信息 </h2>
    <div class="search-result">

      <div class="row jobs-show0"></div>
      <div class="job-table">
        <% @jobs.each do |job| %>
        <div class="row jobs-show">

          <div class="col-md-12 col-lg-9 col-lg-offset-1">

            <div class="pull-right">
              发布时间：<%= job.created_at.to_date %>
            </div>
            <p ><%= link_to(render_highlight_content(job,@query_string),job_path(job)) %></p>

          </div>
        </div>
        <% end %>
      </div>
    </div>
    <div class="text-center">
      <%= will_paginate(@jobs, renderer: BootstrapPagination::Rails) %>
    </div>
  <% end %>
</div>

app/views/jobs/show.html.erb
<h1><%@job.title%></h1>

<p><%= simple_format(@job.description)%></p>

<div class="text-center">
  <%= link_to("投交履历", new_job_resume_path(@job), class:'btn btn-success') %>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Job Listing </title>
        <%= csrf_meta_tags %>

        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>

    <body>

        <div class="container-fluid">
            <%= render "common/navbar" %>
            <%= render "common/flashes" %>
            <div class="row">
              <div class="col-md-2">
                 <ul class="nav nav-pills nav-stacked" style="max-width: 300px; padding-top:20px;">
      <li class="active"><%= link_to("Jobs", admin_jobs_path ) %> </li>

   </ul>

              </div>

              <div class="col-md-10">
                <%= yield %>
              </div>
           </div>
        </div>

        <%= render "common/footer" %>

    </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JobListing</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="shortcut icon"  href="/images/apple.ico">
  </head>

  <body>
  	<div class="container-fluid">
      <div class="row">
        <%= render "common/navbar" %>
        <%= render "common/flashes" %>
        <%= yield %>
      </div>
  	</div>
    
        <%= render "common/footer"%>
  </body>
</html>

app/views/resumes/new.html.erb
<div class="col-md-6 col-md-offset-3">
	<h3> 投交履历到 <%= @job.title %> </h3>

<hr>

<%= simple_form_for [@job, @resume] do |f| %>
  <%= f.input :content ,label:'自我介绍说明',error:'不能为空'%>
  <%= f.input :attachment ,label:'简历附件'%>
  <%= f.submit "提交" ,class:'btn btn-primary'%>
<% end %>

</div>

app/views/welcome/index.html.erb
  <div class="continer">
    <h1 class="title">仙居本地招聘</h1>
    <p class="slogan">让找工作不再困难</p>
    <p class="lead"><a class="btn btn-lg btn-danger" href="/jobs">马上应征</a></p>
  </div>


<div class="content-section-a">
   <div class="container">
     <div class="row">
       <div class="col-lg-5 col-sm-6">
         <hr class="section-heading-spacer">
         <div class="clearfix"></div>
         <h2 class="section-heading">找工作一定要带手机</h2>
         <p class="lead">因为没带手机就不能联络公司</p>
       </div>
       <div class="col-lg-5 col-lg-offset-2 col-sm-6">
         <%= image_tag 'https://raw.githubusercontent.com/niclin/job-listing/25bd6f2c2ffc874c922fda911c17396ca079a04b/app/assets/images/pic-1.jpg', class: 'img-responsive' %>
       </div>
     </div>
   </div>
 </div>
 
 <div class="content-section-b">
   <div class="container">
     <div class="row">
       <div class="col-lg-5 col-lg-offset-1 col-sm-push-6  col-sm-6">
         <hr class="section-heading-spacer">
         <div class="clearfix"></div>
         <h2 class="section-heading">一定要把履历写好在投</h2>
         <p class="lead">履历如果不会写 <a target="_blank" href="http://e6601.com/blog">wo  的 Blog</a></p>
       </div>
       <div class="col-lg-5 col-sm-pull-6  col-sm-6">
         <%= image_tag 'https://raw.githubusercontent.com/niclin/job-listing/25bd6f2c2ffc874c922fda911c17396ca079a04b/app/assets/images/pic-2.jpg', class: 'img-responsive' %>
       </div>
     </div>
   </div>
 </div>
 
 <div class="content-section-a">
   <div class="container">
     <div class="row">
       <div class="col-lg-5 col-sm-6">
         <hr class="section-heading-spacer">
         <div class="clearfix"></div>
         <h2 class="section-heading">这是可以乱改的字<br>动手试试看吧</h2>
         <p class="lead">魔改大赛手稿<a target="_blank" href="https://forum.qzy.camp/">论坛资源</a></p>
       </div>
       <div class="col-lg-5 col-lg-offset-2 col-sm-6">
         <%= image_tag 'https://cdn-standard4.discourse.org/uploads/qzy/original/1X/52c1b8634f4a016d871bf1fcef2b22426cc13511.png', class: 'img-responsive' %>
       </div>
     </div>
   </div>
 </div>